services:
    web:
        container_name: "${PROJECT_NAME}_webserver2"
        build:
            context: .
            dockerfile: Webserver.Dockerfile
        ports:
            - "${PORT_WEBSERVER}:80"
        depends_on:
            - php
            - mysql
        volumes:
            - ./app:/app
            - ./sites-enabled:/etc/apache2/sites-enabled
        restart: always

    php:
        container_name: "${PROJECT_NAME}_php"
        build:
            context: .
            dockerfile: PHP.Dockerfile
        volumes:
            - ./app:/app
        restart: always
        extra_hosts:
            - "api-nonprod.gla.ac.uk:130.209.102.228"
            - "fergus.local:192.168.0.33"

    cron:
        container_name: "${PROJECT_NAME}_cron"
        build:
            context: .
            dockerfile: PHP.Dockerfile
        volumes:
            - ./app:/app
        restart: always

    mysql:
        container_name: "${PROJECT_NAME}_mysql"
        image: mariadb:10.11.15-jammy
        command: --max_allowed_packet=1073741824
        environment:
            MYSQL_ROOT_PASSWORD: 'purple'
            MYSQL_USER: 'moodleuser'
            MYSQL_PASSWORD: 'moodlepass'
            MYSQL_DATABASE: ${DATABASE_NAME}
        restart: always
        volumes:
            - mysqldata:/var/lib/mysql:delegated
        ports:
            - "${PORT_MYSQL}:3306"

    redis:
        container_name: "${PROJECT_NAME}_redis"
        image: redis:latest
        command: redis-server --save "" --appendonly no
        restart: always

volumes:
    mysqldata: {}

