services:
    web:
        container_name: "${PROJECT_NAME}_webserver2"
        build:
            context: .
            dockerfile: Webserver.Dockerfile
        ports:
            - "${PORT_WEBSERVER}:80"
        depends_on:
            - php
            - mysql
        volumes:
            - ./app:/app
            - ./sites-enabled:/etc/apache2/sites-enabled
        restart: always

    php:
        container_name: "${PROJECT_NAME}_php"
        build:
            context: .
            dockerfile: PHP.Dockerfile
        volumes:
            - ./app:/app
        restart: always
        extra_hosts:
            - "api-nonprod.gla.ac.uk:130.209.102.228"
            - "fergus.local:192.168.0.33"

    cron:
        container_name: "${PROJECT_NAME}_cron"
        build:
            context: .
            dockerfile: PHP.Dockerfile
        volumes:
            - ./app:/app
        restart: always

    mysql:
        container_name: "${PROJECT_NAME}_mysql"
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'purple'
            MYSQL_USER: 'moodleuser'
            MYSQL_PASSWORD: 'moodlepass'
            MYSQL_DATABASE: 'moodle45'
        restart: always
        volumes:
            - mysqldata:/var/lib/mysql:delegated
        ports:
            - "${PORT_MYSQL}:3306"

    redis:
        container_name: "${PROJECT_NAME}_redis"
        image: redis:latest
        command: redis-server --save "" --appendonly no
        restart: always

    redisinsight:
        image: redis/redisinsight:latest
        container_name: "${PROJECT_NAME}_insight"
        ports:
            - "${PORT_REDISINSIGHT}:5540"
        environment:
            RI_APP_HOST: 0.0.0.0
        volumes:
            - ./redisinsight:/data

    mailhog:
        image: mailhog/mailhog
        container_name: "${PROJECT_NAME}_mailhog"
        ports:
            - "${PORT_MAILHOG}:8025"

    idp:
        image: kenchan0130/simplesamlphp
        container_name: "${PROJECT_NAME}_idp"
        ports:
            - "${PORT_IDP}:8080"
        environment:
            SIMPLESAMLPHP_SP_ENTITY_ID: "${SP_ENTITY_ID}"
            SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: "${WWWROOT}/auth/saml2/sp/saml2-acs.php/fergus.local"
        volumes:
            - ./authsources.php:/var/www/simplesamlphp/config/authsources.php

volumes:
    mysqldata: {}

